# author: Roy Kid
# contact: lijichen365@126.com
# date: 2021-11-21
# version: 0.0.1

import pytest
from chemRosseta import *
from chemRosseta.general import *

def test_system():
    
    system = System(systemType='MD')

    a = comment('lammps test input file generated by chemRosseta')

    assert a.toLAMMPS() == '# lammps test input file generated by chemRosseta'
    
    assert system.ncommand == 1
    
    assert system.commands[0] == a
    
    echo('both')
    
    assert system.ncommand == 2
    
    assert system.commands[-1].toLAMMPS() == f'echo\tboth'